name = "MPhil"
uuid = "39069ad8-a6fc-4bd9-bc84-dc3c6f3f8497"
authors = ["LiamBlake <liam.blake@adelaide.edu.au>"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
